/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TenstackProvider from "@/util/config/Providers/TenstackProvider";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tamnama",
  description: "Generated by create next app",
};
const iranianSans = localFont({
  src: [
    {
      path: "../public/fonts/YekanBakhFaNum-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={iranianSans.className}>
        <TenstackProvider>{children}</TenstackProvider>
      </body>
    </html>
  );
}
